fruits= []
f2=input("enter fruits :")
fruits.append(f2)
f3=input("enter fruits :")
fruits.append(f3)
f4=input("enter fruits :")
fruits.append(f4)
f5=input("enter fruits :")
fruits.append(f5)
f6=input("enter fruits :")
fruits.append(f6)
f7 = input("Enter fruits name:")
fruits.append(f7)
print(fruits)